export const FETCHING_HABITS = 'FETCHING_HABITS'
export const ADDING_HABIT = 'ADDING_HABIT'
export const DELETING_HABIT = 'DELETING_HABIT'
export const EDITING_HABIT = 'EDITING_HABIT'
export const LOG_HABIT = 'LOG_HABIT'
export const FETCHING_HABITS_LOGS = "FETCHING_HABITS_LOGS"
export const DELETING_HABIT_LOG = "DELETING_HABIT_LOG"
export const FETCHING_HABITS_STATS = "FETCHING_HABITS_STATS"
