# Generated by Django 2.0 on 2018-05-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.CharField(default='default', max_length=8000),
            preserve_default=False,
        ),
    ]
