# Generated by Django 2.0 on 2018-05-11 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_offer_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='cost',
            new_name='price',
        ),
    ]
