# Generated by Django 2.0 on 2018-03-20 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180319_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='Student',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='student_class',
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='api.Class'),
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
    ]
