# Generated by Django 2.0 on 2018-03-20 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180320_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime.now, max_length=8),
        ),
        migrations.AddField(
            model_name='subject',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime.now, max_length=8),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime.now, max_length=8),
        ),
        migrations.AlterField(
            model_name='class',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime.now, max_length=8),
        ),
    ]
