# Generated by Django 2.0 on 2018-03-20 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, max_length=8),
        ),
    ]
