# Generated by Django 2.0 on 2018-03-20 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180320_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_school',
            new_name='school',
        ),
    ]
