# Generated by Django 2.0 on 2018-03-20 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180320_2352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='SchoolClass',
        ),
    ]
