# Generated by Django 2.0 on 2018-03-20 23:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180320_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now, max_length=8)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='school',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='api.Class'),
        ),
        migrations.AlterField(
            model_name='teacherclasssubject',
            name='teacher_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_classe', to='api.Class'),
        ),
        migrations.DeleteModel(
            name='SchoolClass',
        ),
    ]
