# Generated by Django 2.0 on 2018-03-21 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_class_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_checkins', to='api.Student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='api.School'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='api.Class'),
        ),
        migrations.AlterField(
            model_name='teacherclasssubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_class_subject', to='api.Subject'),
        ),
        migrations.AlterField(
            model_name='teacherclasssubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_teacher_class_subject', to='api.Teacher'),
        ),
        migrations.AlterField(
            model_name='teacherclasssubject',
            name='teacher_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_class_subject', to='api.Class'),
        ),
    ]
